---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  ci:
    uses: ./.github/workflows/upstream-ci.yaml
    secrets: inherit
    with:
      default_branch: ${{ github.event.repository.default_branch }}
      event_name: ${{ github.event_name }}
      ref_name: ${{ github.ref_name }}
