---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    if: >
      github.event_name == 'release'
      || (
        github.event_name == 'workflow_run'
        && github.event.workflow_run.conclusion == 'success'
      )
    uses: ./.github/workflows/upstream-deploy.yaml
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
      release_prerelease: ${{ github.event.release.prerelease || false }}
      release_tag_name: ${{ github.event.release.tag_name || '' }}
